[COCO] Enable cutting logic
aalborov/cut_dataset pull request #2
Opened 2019-11-15 16:17 UTC by aalborov

2019-11-15 16:49 UTC, demid5111 requested changes

2019-11-15 16:49 UTC, demid5111 commented on .idea/.gitignore
> +
rm .idea folder + add to gitignore

2019-11-15 16:49 UTC, demid5111 commented on cut_coco.py
> +                        help='Number of images in the output dataset')
does not seem to correspond with the parameter

2019-11-15 16:49 UTC, demid5111 commented on cut_coco.py
> +                        help='Number of images in the output dataset')
required?

2019-11-15 16:49 UTC, demid5111 commented on cut_coco.py
> +def unarchive(source_archive_dir, output_folder_dir):
DRY - Do not Repeat Yourself

2019-11-15 16:49 UTC, demid5111 commented on cut_coco.py
> +def archive(new_file_names, source_path, output_archive_name, output_folder_dir):
🥇

2019-11-15 16:49 UTC, demid5111 commented on cut_coco.py
> +    args = parser().parse_args()
move to the common script

2019-11-15 16:49 UTC, demid5111 commented on cut_coco.py
> +        if 'trainval' and 'annotations' in folder:
use regex

2019-11-15 16:49 UTC, demid5111 commented on cut_coco.py
> +    if len(folders) != 2:
magic constant

2019-11-15 16:49 UTC, demid5111 commented on cut_coco.py
> +        if file_name_l.endswith('.json') and 'instances_val' in file_name_l:
find by regex with system utilities

2019-11-15 16:49 UTC, demid5111 commented on cut_coco.py
> +            if len(annotation_files) > 1:
no need in the check the loop

2019-11-15 16:49 UTC, demid5111 commented on cut_coco.py
> +                sys.exit('Incorrect dataset format. 1')
👍

2019-11-15 16:49 UTC, demid5111 commented on cut_coco.py
> +    if len(images_folder) == 0:
interesting, try something more python-ish

2019-11-15 16:49 UTC, demid5111 commented on cut_coco.py
> +    if first_image >= len(images_folder) - output_size:
move up, need to raise error earlier

2019-11-15 16:49 UTC, demid5111 commented on cut_coco.py
> +    files_to_archive = new_image_filenames
it does not solve immutability pattern

2019-11-18 12:13 UTC, aalborov commented on .idea/.gitignore
> +
done as a separate PR

2019-11-19 09:26 UTC, aalborov commented on cut_coco.py
> +        if len(annotation_files) > 1:
indent

2019-11-19 09:26 UTC, aalborov commented on cut_coco.py
> +        if re.match('annotations_trainval\d{2,4}$', folder):
no loop

2019-11-25 14:08 UTC, aalborov commented
[VOC_sample.zip](https://github.com/aalborov/cut_dataset/files/3886963/VOC_sample.zip)

2019-11-26 06:35 UTC, aalborov commented
[sample_imagenet.zip](https://github.com/aalborov/cut_dataset/files/3890377/sample_imagenet.zip)
[val10.zip](https://github.com/aalborov/cut_dataset/files/3890379/val10.zip)
[annotations_trainval10.zip](https://github.com/aalborov/cut_dataset/files/3890380/annotations_trainval10.zip)

2019-11-26 06:37 UTC, aalborov commented
[VOC_sample.zip](https://github.com/aalborov/cut_dataset/files/3890387/VOC_sample.zip)

2019-11-26 07:26 UTC, aalborov commented on cut_dataset.py
> +    if not is_coco(args.dataset_type):
if isvoc and not args.sourceDir or  :
  exit

2019-11-27 06:02 UTC, merged

2019-11-27 07:13 UTC, aalborov commented
[sample_voc.zip](https://github.com/aalborov/cut_dataset/files/3895549/sample_voc.zip)

2019-11-27 07:16 UTC, aalborov commented
[sample_voc.zip](https://github.com/aalborov/cut_dataset/files/3895560/sample_voc.zip)